# Generated by Django 4.2.9 on 2024-01-31 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_lang',
            field=models.CharField(default='02-03-2007', max_length=250),
            preserve_default=False,
        ),
    ]
